### ISSUE TITLE
Adjust expiration stategy to match time-machine

### ISSUE THREAD

**Issue by joekerna** [laurent22/rsync-time-backup#93] opened 2017-09-25 07:57 UTC
At the moment this script only keeps one backup per month after 31 days.

I would like to keep more old backups because within one month quite a lot can happen that would require more backups steps in between.

In fact the original time-machine backup stragegy states:

> Time Machine saves hourly backups for the past 24 hours, daily backups for the past month, and weekly backups for everything older than a month until the volume runs out of space. At that point, Time Machine deletes the oldest weekly backup. [Wikipedia](https://en.wikipedia.org/wiki/Time_Machine_(macOS))

My suggestion is to also keep one backup per _week_ (not _month_) until the disk is full.

**Comment by laurent22** [comment] 2017-09-26 14:23
Yes this is related to #65. I think rather than changing the strategy (which will be good for some users but not for others), we should have a way to specify the strategy as a command line option. I'm thinking something like this:

    --strategy "Day:1, Month:7, Year:30"

Which would mean: after a day, keep one backup a day, after one month, keep one backup per week (7 days), after one year keep one backup a month (30 days).

Then for example if someone wants to keep only one backup a month, they would have these settings:

    --strategy "Day:1, Month:30, Year:30"

Not sure if the syntax is the best (as, for example, it cannot express "keep backups only for up to 10 days") but basically something like this would be a good flexible solution.

**Comment by markalston** [comment] 2017-09-26 14:34
I think the logic needed to deal with variable amount of days to keep will be pretty complicated.  Not only do you need to check that you are only removing backups that aren't at that date but you need to make sure that a backup for that exact date was made.  If not do you go with the one earlier or after.   Doable but at first glance fairly complicated. 

I was thinking about the weekly backup idea and I think it can be easily done with very minor logic changes by simply appending the week number on the end of the backup folder name.  This way the backups would look like "2017-09-26-123232-39".  Using this naming strategy it becomes trivial to cleanup all but the newest backup for week 10 say.  The current logic for daily and monthly backup retention will not need to change.

The only major downside I see to this strategy is that previous backups will not fit the naming strategy.  This can easily be fixed by checking for old named folders and renaming them with the new method.

**Comment by markalston** [comment] 2017-09-26 14:35
Maybe the rename should actually be "2017-09-26-123232-W39"  So that it is clear at a glance that the 39 is a week number and not the 39th backup for that timestamp.

**Comment by psmanek** [comment] 2017-09-26 15:11
I think strategy solution is the best.

**Comment by psmanek** [comment] 2017-09-26 15:15
I think strategy solution is the best. Please don't change directory naming. Right now YYYY-MM-DD-HHMMSS is really the best solution we can get. Very flexible, manageable and it's very easy to make GUI for it.

**Comment by psmanek** [comment] 2017-09-26 15:16
I think strategy solution is the best set by the --strategy (or something like that) parameter. Please don't change directory naming. Right now YYYY-MM-DD-HHMMSS is really the best solution we can get. Very flexible, manageable and it's very easy to make GUI for it.

**Comment by joekerna** [comment] 2017-09-27 06:01
I really like the _--stragegy_ idea but agree that it can be tricky to implement. Maybe the following algorithm can be easier to implement (example: _--strategy "Month:7"_):

1. Find the first backup of a month and leave it.
2. Delete whatever backups you can find up to 7-1 days ahead.
3. Find the next backup and leave it.
4. Repeat 2. and 3. until the end of the month.

If you have a backup each day you're left with the ones from the 1st, 8th, 15th, 22nd and 29th.
If you didn't run a backup from the 8th until the 11th you're left with 1st, 12th, 19th and 28th.

The gap between the end of one month can be as small as one day but I could live with that.

**Comment by laurent22** [comment] 2017-09-27 18:40
Yes I think your algorithm is the way to go - if we reason in terms of number of days (rather than full weeks/months/years) we don't have to deal with too complicated date manipulations. Actually, in that case, the strategy could even be expressed like this:

    --strategy "1:1, 30:7, 365:30"

Which are pairs of numbers that mean "after x days: keep a backup every y days". So the settings above would mean "After 1 day, keep one backup a day; after 30 days, keep one backup every 7 days; after 365 days, keep one backup every 30 days". Maybe there could be a special meaning for "0", which means after that number of days, don't keep any backup (eg. "10:0" - don't keep anything after 10 days).

Obviously it won't be possible to express certain strategies (like "keep all the backup from last month") since the algorithm will only deal with day offsets, but I think that's acceptable.

**Comment by joekerna** [comment] 2017-09-28 05:37
Why wouldn't it be possible to _keep all the backups from last month_? Wouldn't `--strategy "1:1, 30:30, 365:30` realize that?

- Keep all backups from the last 24 hours
- Keep one backup for each day for the last 30 days
- Keep one backup each 30 days for the last 365 days

Or should the last option be valid indefinitely as in
- Keep one backup each 30 days before 30 days ago

**Comment by mro** [comment] 2017-09-28 20:47
just as a side-note - in a similar project I use iso8601 durations like so: https://github.com/mro/rsync-backup/blob/master/destination/backup-date-filter.lua#L149

**Comment by laurent22** [comment] 2017-10-05 12:16
> Why wouldn't it be possible to keep all the backups from last month? Wouldn't --strategy "1:1, 30:30, 365:30 realize that?

I meant literally if it's 5 September and I want to keep all the backups of the previous month (i.e. from 1 August to 31 August), it won't be possible to specify this, but I guess it doesn't really matter, just being able to keep the backups for the past 30 days would be enough.

> just as a side-note - in a similar project I use iso8601 durations like so: https://github.com/mro/rsync-backup/blob/master/destination/backup-date-filter.lua#L149

That would be better but most likely there's no built-in way in Bash to parse ISO durations and doing it ourselves would make the script too big.

**Comment by joekerna** [comment] 2017-10-05 15:42
What options would we have for the first parameter?
`1:1` means _Keep all backups from the last 24 hours_
`1:0` means _Keep no backup from the last 24 hours_, which would make no sense.
Are there any other options?

**Comment by laurent22** [comment] 2017-10-05 16:00
The format of each interval would be `x:y` which means "after `x` days, keep a backup every `y` days".

So `1:1` means after 24h keep one backup a day. Before 24h, keep all the backups.

For `1:0`, y = 0 would be a special case which means keep no backup after this point. In this case, it would keep no backup after 24h.

At the moment, within the first 24h (or within the first 48h if the first interval is 2:1, etc.) it would keep all the backups. Maybe we also need some way to specify this for users who make a lot of backups every days.

**Comment by joekerna** [comment] 2017-10-05 17:22
That sounds extremely good to me!

**Comment by joekerna** [comment] 2017-11-14 13:16
Any volunteers? :) I'm not very good at bash. Can we divide it into subtasks?

**Comment by laurent22** [comment] 2017-11-17 11:19
Yes sorry I've been meaning to start looking at this but got caught up with other things. I guess a good start would be to write a function to parse the strategy tokens, which could then be used in the section that handles the backup expiration logic.

**Comment by joekerna** [comment] 2017-11-20 10:32
I've started working on parsing the strategy tokens in my fork.

**Comment by joekerna** [comment] 2017-11-20 10:52
Do you have any recommendation what the output format of the parser should be? This would go into the expiration function.

**Comment by laurent22** [comment] 2017-11-21 16:29
I guess an array? But I'm not really familiar with arrays in Bash so not sure what's the best solution.

**Comment by braian87b** [comment] 2017-11-21 18:51
I found this, taken from https://github.com/juliangieseke/TimeBackup/blob/master/tb.sh , it could be useful:

```

# Loglevel defines how much is logged:
# 0 = nothing
# 1 = basic status info
# 2 = more detailed infos (debug/technical stuff)
# 3 = even more debug info
loglevel=0

### log function to add timestamp before string
function _log {
	if [ $loglevel -ge $2 ]; then
		echo $(date "+%F %T") "--" $1
	fi
}

dstpath=''
rexec=''
#Dest: remote host set? 
if [ -n "$dsthost" ]; then
	rexec="ssh $dsthost"
fi
dstpath='/mnt/backups-hd/tm-backups/'
# suffix for monthly, weekly, daily & hourly backups
fnamemonth='m'
fnameweek='w'
fnameday='d'
fnamehour='h'
# keep backups n days, used with -mtime
keephourly=1
keepdaily=14
keepweekly=56 #8 * 7
keepmonthly=504 # 18 * 4 * 7

#cleanup function, deletes old backups
function _cleanup {
	found="$($rexec find $dstpath -maxdepth 1 -mtime +$1 -name "$2" -type d)"
	for f in $found; do
		_log "deleting $f" 1
		$rexec rm -r "$f"
	done
}
_log "cleaning up." 1
if $rexec [ -d "$dstpath$incomplete" ]; then 
	_log "deleting $dstpath$incomplete" 1
	$rexec rm -r "$dstpath$incomplete"
fi
_cleanup "$keephourly" "$findpattern$fnamehour*"
_cleanup "$keepdaily" "$findpattern$fnameday*"
_cleanup "$keepweekly" "$findpattern$fnameweek*"
_cleanup "$keepmonthly" "$findpattern$fnamemonth*"


```

**Comment by braian87b** [comment] 2017-11-21 21:14
I found this, taken from https://github.com/juliangieseke/TimeBackup/blob/master/tb.sh , it could be useful:

```

# Loglevel defines how much is logged:
# 0 = nothing
# 1 = basic status info
# 2 = more detailed infos (debug/technical stuff)
# 3 = even more debug info
loglevel=0

### log function to add timestamp before string
function _log {
	if [ $loglevel -ge $2 ]; then
		echo $(date "+%F %T") "--" $1
	fi
}

dstpath=''
rexec=''
#Dest: remote host set? 
if [ -n "$dsthost" ]; then
	rexec="ssh $dsthost"
fi
dstpath='/mnt/backups-hd/tm-backups/'
# suffix for monthly, weekly, daily & hourly backups
fnamemonth='m'
fnameweek='w'
fnameday='d'
fnamehour='h'
# keep backups n days, used with -mtime
keephourly=1
keepdaily=14
keepweekly=56 #8 * 7
keepmonthly=504 # 18 * 4 * 7

#cleanup function, deletes old backups
function _cleanup {
	found="$($rexec find $dstpath -maxdepth 1 -mtime +$1 -name "$2" -type d)"
	for f in $found; do
		_log "deleting $f" 1
		$rexec rm -r "$f"
	done
}
_log "cleaning up." 1
if $rexec [ -d "$dstpath$incomplete" ]; then 
	_log "deleting $dstpath$incomplete" 1
	$rexec rm -r "$dstpath$incomplete"
fi
_cleanup "$keephourly" "$findpattern$fnamehour*"
_cleanup "$keepdaily" "$findpattern$fnameday*"
_cleanup "$keepweekly" "$findpattern$fnameweek*"
_cleanup "$keepmonthly" "$findpattern$fnamemonth*"


```

**Comment by joekerna** [comment] 2017-11-24 19:31
I've finished the parser in #99. Please test it. Please remember, it's only the parser of the option. Expiration strategy is still the same.

**Comment by laurent22** [comment] 2017-11-26 17:09
I've moved the change to [this branch](https://github.com/laurent22/rsync-time-backup/tree/expiration-strategy) so that the logic can be beta-tested for a month or two before we move it to master. Is there any chance anyone interested could give it a try?

What I've been doing for testing is create a bunch of fake backup folders and then run the backup script on them. I was using several variations of the script below - in that version it creates 1400 folders over two years with 2 folders per day:

```
<?php

$d = new DateTime();
$d->sub(new DateInterval('P700D'));

for ($i = 0; $i < 1400; $i++) {
	$d->add(new DateInterval('PT12H'));
	mkdir("/path/to/TestDest/" . $d->format('Y-m-d-His'));
}
```

Then I would run this for each test:

    rm -rf /path/to/TestDest/201* && php create_folders.php && ./rsync_tmbackup.sh /path/to/TestSource/ /path/to/TestDest/

As far as I can tell it's working, but if anyone could give it a try to confirm that would be great.

**Comment by pagaille** [comment] 2018-01-09 21:34
What about that statement :

> At that point, Time Machine deletes the oldest weekly backup. Wikipedia

I really like that feature because it allows the backup to run indefinitely (provided the source backup fits the target size of course) without any user interaction.

**Comment by laurent22** [comment] 2018-02-23 17:49
Duplicate of #105

**Closed by laurent22** 2018-02-23 17:49 UTC
Labels: enhancement
